repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0  # Use the version you have installed
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        types: [file]
        additional_dependencies:
          - eslint@8.56.0
          - '@typescript-eslint/parser'
          - '@typescript-eslint/eslint-plugin'
          - 'eslint-plugin-react'
          - 'eslint-plugin-react-hooks' 