name: Deploy Database Stack
on:
    workflow_dispatch:
        inputs:
            env_name:
                description: 'Environment name (e.g., staging, production)'
                required: true
                default: 'staging'
permissions:
    contents: read
    id-token: write
jobs:
    deploy:
        environment: ${{ github.event.inputs.env_name }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3

            - name: Set up AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }}
                aws-region: eu-west-2
            
            - name: Install AWS CDK
              run: npm install -g aws-cdk
            
            - name: Deploy CDK (Database Stack)
              run: |
                cd infra
                cdk deploy DatabaseStack -c env_name=${{ github.event.inputs.env_name }} --require-approval never --verbose
              
            

              